### ISSUE TITLE
运行RAG

### ISSUE THREAD

**Issue by jerryhbue** [toddlt/agiclass-issue#1]
将RAG代码拷贝出来单独做成python文件，运行报错，信息如下：`

  File "e:\gpt\rag.py", line 9, in <module>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonvirtualenvs\openai12\Lib\site-packages\nltk\decorators.py", line 94, in update_wrapper
    infodict = infodict or getinfo(model)
                           ^^^^^^^^^^^^^^
  File "D:\pythonvirtualenvs\openai12\Lib\site-packages\nltk\decorators.py", line 67, in getinfo
    signature = inspect.formatargspec(
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'formatargspec'. Did you mean: 'formatargvalues'?

=====
主要是导入模块的代码出错：
`from openai import OpenAI
import os
from dotenv import load_dotenv,find_dotenv

from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer

from elasticsearch7 import Elasticsearch, helpers
from nltk.stem import PorterStemmer   // 这是报错的第9行
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
import re`

运行环境：python3.11.6

anyio              3.7.1
certifi            2023.7.22
cffi               1.16.0
charset-normalizer 3.3.2
colorama           0.4.6
cryptography       41.0.5
distro             1.8.0
elasticsearch7     7.17.9
h11                0.14.0
httpcore           1.0.2
httpx              0.25.1
idna               3.4
nltk               3.4.5
openai             1.2.4
pdfminer.six       20221105
pip                23.3.1
pycparser          2.21
pydantic           1.10.13
python-dotenv      1.0.0
setuptools         68.2.2
six                1.16.0
sniffio            1.3.0
tqdm               4.66.1
typing_extensions  4.8.0
urllib3            1.26.18
wheel              0.41.3
wrapt              1.14.0

**Comment by toddlt** [comment]
贴一下你的代码和报错截图呗

**Comment by toddlt** [comment]
inspect下的函数很多已经是deprecated的了， 在python 3.10之前还是可用的，3.11就不支持了

解决办法2种：
1. 升级nltk到最新（我试了python3.11+nltk3.8.1可以）
2. 降级python版本到3.9（老师的实验环境用的3.9）

参考：
https://stackoverflow.com/questions/74585622/pyfirmata-gives-error-module-inspect-has-no-attribute-getargspec
https://github.com/pyinvoke/invoke/issues/833
